apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-dev
  namespace: argocd
spec:
  destination:
    namespace: dev 
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes-manifests/dev
    repoURL: https://github.com/rne1223/nd064_capstone_starter
    targetRevision: HEAD
  # Sync policy automated to get all the changes from github automatically
  syncPolicy: 
    automated: {}